//AUTH ACTIONS
export const SAVE_TOKEN = "SAVE_TOKEN";
export const SAVE_SESSION = "SAVE_SESSION";

//MOVIES ACTIONS
export const ADD_MOVIE = "ADD_MOVIE";
export const FETCH_MOVIES = "FETCH_MOVIES";

//FAVORITES ACTIONS

export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
